### ISSUE TITLE
Both versions don't work on Safari

### ISSUE THREAD

**Issue by WebFactoryLtd** [BrooonS/TimezZ#1]
Hi,
On Safari 11.0.2 the new version of the plugin (expectedly) doesn't work because of the ellipsis. But the old ES6 doesn't work either :( All numbers (days, hours ..) are NaN. Any idea how to fix?

Thank you!

**Comment by letstri** [comment]
Thx for issue, i fix it in soon.

**Comment by WebFactoryLtd** [comment]
Thank you!

I tried the old, jQuery version too. Safari insists on NaN :( Really don't know why. It's simple math.

**Comment by letstri** [comment]
Try this version https://github.com/BrooonS/TimezZ/releases/tag/3.1.0

**Comment by WebFactoryLtd** [comment]
Thank you for the super-fast update!

Unfortunately still getting NaN :(
Page I'm testing on - https://comingsoonwp.com/theme-preview/?theme=writing-service-video
Works on absolutely every other browser except Safari. Really don't get it.

Upgrading to Safari 11.1 to see if it'll help.

**Comment by WebFactoryLtd** [comment]
Updated to Safari 11.1 - nothing :(
With console set to "report all" it shows nothing. Just NaN for all numbers.

**Comment by letstri** [comment]
Okey, i try to fix it in soon, again.

**Comment by WebFactoryLtd** [comment]
Found the issue!!!
Safari is very picky and can only process date if it's in "January 1, 2040 00:00:00" format. I used "2018-04-30 11:11" and that caused the problem.

So definitely not your fault! Thank you for your time!
