### ISSUE TITLE
How to display "year"?

### ISSUE THREAD

**Issue by note4** [BrooonS/TimezZ#16]
If I want to add a "year" before the first unit "day", how do I display the "year"?

如果我要把第一个单位”天“前面再加一个”年“，请问如何显示"年"？

` canContinue: true,` Is it mandatory?

` canContinue: true,` 是否是必须配置的？

**Comment by letstri** [comment]
Hello,

Now year you can't add, but I'll add it in the next release.

As you can see in types
https://github.com/BrooonS/timezz/blob/master/dist/timezz.d.ts
`canContinue` is a optional
