### ISSUE TITLE
6.1.0: iOS doesn't display properly

### ISSUE THREAD

**Issue by note4** [BrooonS/TimezZ#18]
It can be displayed normally on both the computer and the Android mobile phone, but not on iOS. What is the reason?
我按住 README 中指引进行操作，电脑上 Chrome 和 Android 上Chrome 都可以正常显示，但是在 iOS 设备上（Chrome 和 Safari）无法正常显示倒计时，

views（timezz@6.1.0)
案例：基于 timezz 6.1.0

https://123.1px.run/time/test/

**Comment by letstri** [comment]
Hello, sorry for the delay, I fixed it in the new version.
iOS and macOS couldn't parse strings dates.
