### ISSUE TITLE
4.0.1: How to modify the initialization time zone?

### ISSUE THREAD

**Issue by note4** [BrooonS/TimezZ#19]
I found that timezz@4.0.1 uses UTC0 (Universal Coordinated Time) for countdown by default. How do I initialize the time zone?
demo: https://123.1px.run/time/

发现 timezz@4.0.1 默认使用的是 UTC0 （世界协调时）进行倒计时，请问我应该如何初始化时区？
案例：https://123.1px.run/time/

**Comment by letstri** [comment]
If I correct understand, you need to call `timezz` with the needed timezone.

For example:

```js
const date = moment(YOUR_DATE).utc().valueOf();
```

and init timezz with this date.
