### ISSUE TITLE
Continue with minutes instead of displaying hours after 59:59

### ISSUE THREAD

**Issue by maximus1127** [BrooonS/TimezZ#29]
Hi, is there a way to continue counting up in minutes instead of transitioning from 59:59 to 01:00:00. In this example, it would start counting up to 60:00 and then a minute later 61:00 etc...

**Comment by letstri** [comment]
Hi, I'll update the lib. I want to add calculations only for existing DOM elements in timer.

**Comment by maximus1127** [comment]
oh what glorious news!!! This will add that little extra sauce to my project. Greatly appreciated.

**Comment by letstri** [comment]
@maximus1127 Done.

**Comment by maximus1127** [comment]
wonderful! what's the parameter to activate this new feature?

**Comment by letstri** [comment]
@maximus1127 you can remove not needed data attributes, in your case I think this variant will be correct: 
```
<div class="j-timer">
  <span data-minutes></span>
  <span data-seconds></span>
</div>
```

**Comment by maximus1127** [comment]
![image](https://user-images.githubusercontent.com/31026284/160396814-9d3b1b98-846f-4120-b72d-e21aa78a4daf.png)

Hmm, i swapped out the code in my project for the latest file in your dist folder and removed my hours html element and got this error in the console. Did I do that upgrade process correctly?

**Comment by letstri** [comment]
I changed selectors to HTML Element, you need to initialize with document.querySelector, or something like that. Read documentation for more info)
