### ISSUE TITLE
TypeScript Error: TS2769 in timezz.ts line 325

### ISSUE THREAD

**Issue by richardaubin** [BrooonS/TimezZ#35]
I'm encountering an error in my IDE:

![image](https://github.com/letstri/timezz/assets/37956997/9b93c171-e899-4ee1-b735-761cd25c1dfd)

Line 139 assigns NodeJS.Timer to the timeout variable:
` private timeout: NodeJS.Timer | null = null;`

If I change the type to NodeJS.Timeout, the error goes away.

This is possibly due to the type of environment the code is excecuted in.

I'm not a Node or JS guy...  but this is what ChatGPT has to say:

![image](https://github.com/letstri/timezz/assets/37956997/31b242da-fe41-48ca-82bc-20e3c0b1bae8)

So it might appear that my application is working in a Node.js environment, and not in a browser environment.

**Comment by letstri** [comment]
Hello, thank you for issue.

I've released a new version, can you try it now?

**Comment by letstri** [comment]
I've release a new version, can you try it now?

**Comment by richardaubin** [comment]
The code that my build is importing is from an assets folder in a 3rd party theme.

The code in the timerzz.ts file is exactly what I shown in the original issue.
` private timeout: NodeJS.Timer | null = null;`

Is it possible the author the theme has modified the code?  Because I have viewed the code here in the master branch at version 7 and it was ReturnType... as you stated in the previously edited comment.

The package however does require the npm dependency of version 7.0.0 which leaves me to wonder if the theme author has edited the original code..

**Comment by letstri** [comment]
I fixed it in 8 version, so you can update the `timezz` and try again.

**Comment by richardaubin** [comment]
The code doesn't appear to have changed in the zip file:
![image](https://github.com/letstri/timezz/assets/37956997/329122e3-09ad-4a4d-9003-8f1ab93c9210)

I've notified the theme author of the issue, and sent him a link to this thread.

Let's see what he has to say?

**Comment by letstri** [comment]
Yes, off course, he should just update the `timezz` version to 8. Also, can you share a link to the theme?

**Comment by richardaubin** [comment]
Cartzilla | Multipurpose E-Commerce Bootstrap HTML Template (createx.studio)<https://cartzilla.createx.studio/index.html>
