### ISSUE TITLE
Feature to stop the countdown 

### ISSUE THREAD

**Issue by mtness** [BrooonS/TimezZ#5]
Hi there,
First of all, thank you very much for this magnificent script!

I was wondering if there is a possibility to just stop the countdown on the given time, but I was surprised that it seems this in't possible at all?!

However, this is just a small touchup of your script.
Unfortunately, I don't have a gulp environment right now to build this here -
 the needed logic here is like this:
add option: `stop: 1`

and
`
if(stop && distance<0 ) {
	isStopped=1;
	countDays  = 0;
	countHours  = 0;
	countMinutes  = 0;
	countSeconds  = 0;
}
`
should go to line 63 of timezz.js

Best regards, MT

**Comment by letstri** [comment]
Hi, mtness, in a week i will release a new version. Thx for issue.
